options(shiny.maxRequestSize=400*1024^2)

GROUP_FEATURE_NAME <- "__grandforest__group__"

DEFAULT_NUM_FEATURES <- 20
MIN_NUM_FEATURES <- 1
MAX_NUM_FEATURES <- 100

DEFAULT_NUM_TREES <- 2000
MIN_NUM_TREES <- 100
MAX_NUM_TREES <- 5000

MIN_NUM_CLUSTERS <- 2
MAX_NUM_CLUSTERS <- 12
DEFAULT_NUM_CLUSTERS <- 2
