options(shiny.maxRequestSize=400*1024^2)
options(spinner.type=5)

APP_VERSION <- "0.1-preview"

GROUP_FEATURE_NAME <- "__grandforest__group__"

DEFAULT_NUM_FEATURES <- 20
MIN_NUM_FEATURES <- 1
MAX_NUM_FEATURES <- 100

DEFAULT_NUM_TREES <- 2000
MIN_NUM_TREES <- 100
MAX_NUM_TREES <- 5000

MIN_NUM_CLUSTERS <- 2
MAX_NUM_CLUSTERS <- 12
DEFAULT_NUM_CLUSTERS <- 2

MAX_TARGET_NETWORK_NODES <- 500

MISSING_GENE_WARNING <- 0.5

EXAMPLE_DATA_PATH <- "data/brca.os.subtypes.LumAB.rds"
EXAMPLE_DATA_CLUSTERVAR <- "subtype"
EXAMPLE_DATA_TIMEVAR <- "os_time"
EXAMPLE_DATA_STATUSVAR <- "os_status"
